Repository Janaza/D7024E, pull requests merged in 2019-10, with the labels that each got.

#55 Find_value working
  kademlia.go
  main/main.go
  network.go
Labels: Go, Sprint-2

#57 CLI progress
  cli.go
  kademlia.go
  main/main.go
  network.go
Labels: Go, Sprint-2, bug

#58 Gt 44 containerization
  compose/compose.go
  compose/docker-compose.yml
  compose/init/bootstrap/init.sh
  compose/init/node/init.sh
  main/Dockerfile
  main/init/bootstrap/init.sh
  main/init/node/init.sh
  main/run.sh
Labels: Docker, Urgent

#72 Readme file
  README.md
Labels: Sprint-2, documentation
